conn / as sysdba

CREATE PLUGGABLE DATABASE imds4A ADMIN USER etu IDENTIFIED BY imds4A
FILE_NAME_CONVERT=('opt/oracle/oradata/FREE/','opt/oracle/oradata/FREE/imds4A');

ALTER PLUGGABLE DATABASE IMDS4A OPEN READ WRITE ;
ALTER PLUGGABLE DATABASE ALL OPEN;

ALTER SESSION set container=imds4a;


GRANT CREATE SESSION TO etu;
GRANT CREATE ANY TABLE, 
      CREATE ANY VIEW,
      SELECT ANY TABLE, 
      UPDATE ANY TABLE, 
      DELETE ANY TABLE, 
      INSERT ANY TABLE,
      ALTER ANY TABLE, 
      DROP ANY TABLE, 
      BACKUP ANY TABLE, 
      FLASHBACK ANY TABLE, 
      GRANT ANY OBJECT PRIVILEGE
   TO etu WITH ADMIN OPTION;

ALTER USER etu QUOTA UNLIMITED ON SYSTEM;